/* GENERATED by measure/gen-slots.mjs — do not hand-edit.
 *
 * Neutral filler, sized by MEASURING the wrap in a real layout at the
 * reference's box width and type role, so each slot occupies exactly the
 * number of lines the reference measures there. None of the reference's words
 * are used; replace these strings with your own copy.
 *
 * slot: box width x line count @ type role
 *   heroHeadline             764px x 2 line(s) @ 72px
 *   heroSub                  540px x 2 line(s) @ 18px
 *   heroStrapL               575px x 1 line(s) @ 14px
 *   heroStrapR               575px x 1 line(s) @ 14px
 *   pillarsHeading           560px x 2 line(s) @ 52px
 *   pillarsItemTitle         560px x 1 line(s) @ 20px
 *   pillarsItemBody          560px x 1 line(s) @ 16px
 *   pillarsCardName       275.89px x 1 line(s) @ 20px
 *   pillarsCardRole       275.89px x 1 line(s) @ 12px
 *   servicesHeading          696px x 2 line(s) @ 52px
 *   servicesCardTitle        332px x 1 line(s) @ 24px
 *   servicesCardBody         380px x 2 line(s) @ 16px
 *   frameworkHeading         744px x 2 line(s) @ 52px
 *   frameworkStepTitle       346px x 1 line(s) @ 20px
 *   frameworkStepBody        346px x 3 line(s) @ 16px
 *   casesHeading             744px x 2 line(s) @ 52px
 *   casesPlateTitle          410px x 1 line(s) @ 24px
 *   casesPlateBody           410px x 8 line(s) @ 16px
 *   approachHeading          550px x 3 line(s) @ 52px
 *   approachRowTitle         270px x 1 line(s) @ 24px
 *   approachRowBody          550px x 5 line(s) @ 16px
 *   approachCardCta          212px x 1 line(s) @ 16px
 *   testimonialsHeading      774px x 2 line(s) @ 52px
 *   testimonialQuote         316px x 5 line(s) @ 24px
 *   testimonialQuote3        316px x 3 line(s) @ 24px
 *   testimonialName          296px x 1 line(s) @ 20px
 *   testimonialRole          296px x 1 line(s) @ 12px
 *   videoLabel               316px x 1 line(s) @ 16px
 *   videoMeta                316px x 1 line(s) @ 14px
 *   faqHeading               494px x 2 line(s) @ 52px
 *   faqQ1                    520px x 2 line(s) @ 20px
 *   faqQ2                    520px x 1 line(s) @ 20px
 *   faqQ3                    520px x 2 line(s) @ 20px
 *   faqQ4                    520px x 2 line(s) @ 20px
 *   faqQ5                    520px x 1 line(s) @ 20px
 *   faqAnswer                554px x 6 line(s) @ 16px
 *   faqCardTitle             454px x 1 line(s) @ 16px
 *   faqCardSub               454px x 1 line(s) @ 14px
 *   footerHeading            576px x 2 line(s) @ 52px
 *   footerLead               480px x 3 line(s) @ 18px
 *   footerSignupLabel      171.7px x 1 line(s) @ 20px
 *   footerConsent          678.3px x 1 line(s) @ 14px
 *   footerCardCta            212px x 1 line(s) @ 16px
 *   footerAddress            160px x 3 line(s) @ 14px
 *   footerCopyright       521.48px x 1 line(s) @ 14px
 *   footerCredit           521.5px x 1 line(s) @ 14px
 *   megaTitle                666px x 1 line(s) @ 16px
 *   megaItemTitle            606px x 1 line(s) @ 16px
 *   megaItemBody             606px x 1 line(s) @ 14px
 *   megaFeatureTitle         372px x 1 line(s) @ 24px
 *   megaFeatureBody          372px x 3 line(s) @ 14px
 *   heroPrimaryCta       fitted to   85.06px wide  (got 85) @ 16px
 *   heroSecondaryCta     fitted to  139.22px wide  (got 139.48) @ 16px
 *   navLink1             fitted to    40.7px wide  (got 40.72) @ 15px
 *   navLink2             fitted to   58.47px wide  (got 58.34) @ 15px
 *   navLink3             fitted to   87.14px wide  (got 87.25) @ 15px
 *   navLink4             fitted to    53.5px wide  (got 53.44) @ 15px
 *   navSub1              fitted to  116.48px wide  (got 115.91) @ 14px
 *   navSub2              fitted to  119.94px wide  (got 120.38) @ 14px
 *   navSub3              fitted to  155.89px wide  (got 155.83) @ 14px
 *   navCta               fitted to   85.06px wide  (got 85) @ 16px
 *   pillarsCardCta       fitted to  106.11px wide  (got 106.2) @ 16px
 *   casesLink            fitted to  104.73px wide  (got 104.52) @ 16px
 *   footerSignupLabel2   fitted to   171.7px wide  (got 171.56) @ 20px
 *   footerLink1          fitted to    37.7px wide  (got 37.7) @ 14px
 *   footerLink2          fitted to    38.3px wide  (got 38.34) @ 14px
 *   footerLink3          fitted to   84.28px wide  (got 84.55) @ 14px
 *   footerLink4          fitted to   50.64px wide  (got 50.67) @ 14px
 *   footerLink5          fitted to   50.89px wide  (got 50.91) @ 14px
 *   footerLegal1         fitted to   88.64px wide  (got 88.66) @ 14px
 *   footerLegal2         fitted to  122.55px wide  (got 122.5) @ 14px
 *   footerLinksLabel     fitted to   38.05px wide  (got 37.77) @ 12px
 *   footerLegalLabel     fitted to   41.61px wide  (got 41.73) @ 12px
 *   footerCreditLink     fitted to   31.47px wide  (got 31.5) @ 14px
 */
export const SLOT_TEXT = {
  heroHeadline: "[HEADLINE] placeholder copy sized to the",
  heroSub: "[SUB] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words",
  heroStrapL: "[STRAP L] placeholder copy sized to the measured box so the layout can be verified",
  heroStrapR: "[STRAP R] placeholder copy sized to the measured box so the layout can be verified",
  pillarsHeading: "[HEADING] placeholder copy sized to the",
  pillarsItemTitle: "[ITEM] placeholder copy sized to the measured box so the",
  pillarsItemBody: "[BODY] placeholder copy sized to the measured box so the layout can be",
  pillarsCardName: "[NAME] placeholder copy sized",
  pillarsCardRole: "[ROLE] placeholder copy sized to the",
  servicesHeading: "[HEADING] placeholder copy sized to the measured box so the",
  servicesCardTitle: "[CARD] placeholder copy sized",
  servicesCardBody: "[BODY] placeholder copy sized to the measured box so the layout can be verified against the",
  frameworkHeading: "[HEADING] placeholder copy sized to the measured box so the layout",
  frameworkStepTitle: "[STEP] placeholder copy sized to the",
  frameworkStepBody: "[BODY] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its",
  casesHeading: "[HEADING] placeholder copy sized to the measured box so the layout",
  casesPlateTitle: "[PLATE] placeholder copy sized to the",
  casesPlateBody: "[BODY] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as long as the box needs  placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as long as the box needs  placeholder copy sized to the measured box so the layout can be verified against the",
  approachHeading: "[HEADING] placeholder copy sized to the measured box so the",
  approachRowTitle: "[ROW] placeholder copy",
  approachRowBody: "[BODY] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as long as the box needs  placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as long as the box needs",
  approachCardCta: "[CARD CTA] placeholder",
  testimonialsHeading: "[HEADING] placeholder copy sized to the measured box so the layout can",
  testimonialQuote: "[QUOTE] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it",
  testimonialQuote3: "[QUOTE] placeholder copy sized to the measured box so the layout can be verified",
  testimonialName: "[NAME] placeholder copy sized",
  testimonialRole: "[ROLE] placeholder copy sized to the",
  videoLabel: "[PLAY] placeholder copy sized to the",
  videoMeta: "[LENGTH] placeholder copy sized to the",
  faqHeading: "[HEADING] placeholder copy sized to the",
  faqQ1: "[Q1] placeholder copy sized to the measured box so the layout can be verified against the reference without",
  faqQ2: "[Q2] placeholder copy sized to the measured box so the",
  faqQ3: "[Q3] placeholder copy sized to the measured box so the layout can be verified against the reference without",
  faqQ4: "[Q4] placeholder copy sized to the measured box so the layout can be verified against the reference without",
  faqQ5: "[Q5] placeholder copy sized to the measured box so the",
  faqAnswer: "[ANSWER] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as long as the box needs  placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as long as the box needs  placeholder copy sized to the measured box so the layout can be verified",
  faqCardTitle: "[CARD TITLE] placeholder copy sized to the measured box",
  faqCardSub: "[CARD SUB] placeholder copy sized to the measured box so the layout",
  footerHeading: "[HEADING] placeholder copy sized to the measured",
  footerLead: "[LEAD] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as long as",
  footerSignupLabel: "[SIGN UP]",
  footerConsent: "[CONSENT] placeholder copy sized to the measured box so the layout can be verified",
  footerCardCta: "[CARD CTA] placeholder",
  footerAddress: "[ADDRESS] placeholder copy sized to the measured box so the",
  footerCopyright: "[COPYRIGHT] placeholder copy sized to the measured box so the layout can be",
  footerCredit: "[CREDIT] placeholder copy sized to the measured box so the layout can",
  megaTitle: "[MEGA] placeholder copy sized to the measured box so the layout can be verified against",
  megaItemTitle: "[ITEM] placeholder copy sized to the measured box so the layout can be verified",
  megaItemBody: "[ITEM BODY] placeholder copy sized to the measured box so the layout can be verified against",
  megaFeatureTitle: "[FEATURE] placeholder copy sized",
  megaFeatureBody: "[FEATURE BODY] placeholder copy sized to the measured box so the layout can be verified against the reference without borrowing its words and it keeps running for as",
  heroPrimaryCta: "[CTA] d to t",
  heroSecondaryCta: "[CTA 2] r copy size",
  navLink1: "[A] r c",
  navLink2: "[B] older",
  navLink3: "[C] older cop",
  navLink4: "[D] lder ",
  navSub1: "[SUB 1] d to the m",
  navSub2: "[SUB 2] red box so",
  navSub3: "[SUB 3] e measured box",
  navCta: "[CTA] d to t",
  pillarsCardCta: "[LINK] er copy",
  casesLink: "[LINK]  sized t",
  footerSignupLabel2: "[SIGN UP] zed to th",
  footerLink1: "[1] iiiiii",
  footerLink2: "[2] r c",
  footerLink3: "[3] placehold",
  footerLink4: "[4] ured",
  footerLink5: "[5] llllllll",
  footerLegal1: "[LEGAL 1] e m",
  footerLegal2: "[LEGAL 2] e measu",
  footerLinksLabel: "[L] op",
  footerLegalLabel: "[LG] y ",
  footerCreditLink: "[C] ...",
} as const;

export type SlotKey = keyof typeof SLOT_TEXT;
