import { launch, Session } from './cdp.mjs';
import { setTimeout as sleep } from 'node:timers/promises';
const { proc, wsUrl } = await launch({ port: 9970, width: 1440, height: 900 });
const s = await Session.connect(wsUrl);
await s.attachToPage(); await s.send('Page.enable'); await s.send('Runtime.enable');
await s.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
const loaded=new Promise(r=>s.on('Page.loadEventFired',r));
await s.send('Page.navigate',{url:'http://localhost:3111/'});
await Promise.race([loaded,sleep(20000)]); await sleep(2500);
console.log('h1 span count:', await s.eval(`document.querySelectorAll('h1 span').length`));
console.log('reveal-word count:', await s.eval(`document.querySelectorAll('.reveal-word').length`));
console.log('data-revealed wrappers:', await s.eval(`[...document.querySelectorAll('[data-revealed]')].map(e=>e.getAttribute('data-revealed')).slice(0,6).join(',')`));
console.log('first reveal-word computed:', await s.eval(`(()=>{const e=document.querySelector('.reveal-word');if(!e)return 'none';const c=getComputedStyle(e);
  return 'op:'+c.opacity+' tf:'+c.transform+' filter:'+c.filter+' transition:'+c.transitionDuration+' delay:'+c.transitionDelay+' display:'+c.display})()`));
console.log('--ease-reveal defined:', await s.eval(`getComputedStyle(document.documentElement).getPropertyValue('--ease-reveal').slice(0,60) || '(empty)'`));
console.log('hero img animation:', await s.eval(`(()=>{const e=document.querySelector('.hero-appear');if(!e)return 'none';const c=getComputedStyle(e);
  return 'name:'+c.animationName+' dur:'+c.animationDuration+' fill:'+c.animationFillMode+' op:'+c.opacity+' tf:'+c.transform})()`));
s.close(); proc.kill('SIGKILL'); process.exit(0);
