import { readFileSync } from 'node:fs';
const d = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const byPath = new Map(d.nodes.map(n=>[n.path,n]));
const parent = n => { const i=n.path.lastIndexOf('/'); return i<0?null:byPath.get(n.path.slice(0,i)); };
const sig = n => {
  if (['script','style','link'].includes(n.tag)) return false;
  if (n.text) return true;
  if (n.img || n.svgAttrs) return true;
  if (n.backgroundColor!=='rgba(0, 0, 0, 0)' || n.backgroundImage!=='none') return true;
  if ([n.radiusTL,n.radiusTR,n.radiusBR,n.radiusBL].some(v=>v!=='0px')) return true;
  if (!n.borderTop.startsWith('0px')||!n.borderRight.startsWith('0px')||!n.borderBottom.startsWith('0px')||!n.borderLeft.startsWith('0px')) return true;
  if (n.boxShadow!=='none' || n.backdropFilter!=='none' || n.filter!=='none' || n.opacity!=='1') return true;
  if (n.gridTemplateColumns!=='none') return true;
  if ((n.rowGap!=='normal'&&n.rowGap!=='0px')||(n.columnGap!=='normal'&&n.columnGap!=='0px')) return true;
  if ([n.paddingTop,n.paddingRight,n.paddingBottom,n.paddingLeft].some(v=>v!=='0px')) return true;
  if (n.transform!=='none' || n.position==='absolute' || n.position==='fixed' || n.position==='sticky') return true;
  const p = parent(n);
  if (!p) return true;
  if (Math.abs(p.w-n.w)>0.5 || Math.abs(p.h-n.h)>0.5 || Math.abs(p.x-n.x)>0.5 || Math.abs(p.y-n.y)>0.5) return true;
  return false;
};
const rr = n => { const a=[n.radiusTL,n.radiusTR,n.radiusBR,n.radiusBL]; return a.every(v=>v===a[0])?(a[0]==='0px'?'':' r:'+a[0]):' r:'+a.join('/'); };
console.log(`### ${d.name}  root y${d.box.y} x${d.box.x} ${d.box.w}×${d.box.h}  (${d.count} nodes, ${d.nodes.filter(sig).length} significant)`);
for (const n of d.nodes) {
  if (!sig(n)) continue;
  const rel = n.path.slice(d.root.length) || 'ROOT';
  const short = rel.replace(/\/(\w+)\[(\d+)\]/g, (m,t,i)=>'/'+t+i);
  const bits = [];
  bits.push(`${n.display}${n.display.includes('flex')?'-'+n.flexDirection[0]+(n.flexWrap!=='nowrap'?'/wrap':''):''}`);
  if (n.display.includes('flex')||n.display==='grid') bits.push(`ai:${n.alignItems.replace('flex-','')} jc:${n.justifyContent.replace('flex-','')}`);
  if (n.gridTemplateColumns!=='none') bits.push(`COLS[${n.gridTemplateColumns}]`);
  if (n.gridTemplateRows!=='none') bits.push(`ROWS[${n.gridTemplateRows}]`);
  const g=[]; if(n.rowGap!=='normal'&&n.rowGap!=='0px')g.push('row '+n.rowGap); if(n.columnGap!=='normal'&&n.columnGap!=='0px')g.push('col '+n.columnGap);
  if(g.length)bits.push('gap('+g.join(', ')+')');
  const pad=[n.paddingTop,n.paddingRight,n.paddingBottom,n.paddingLeft]; if(pad.some(v=>v!=='0px'))bits.push('pad '+pad.join(' '));
  const mar=[n.marginTop,n.marginRight,n.marginBottom,n.marginLeft]; if(mar.some(v=>v!=='0px'))bits.push('mar '+mar.join(' '));
  if(n.position!=='static'&&n.position!=='relative')bits.push(`${n.position} t${n.top} r${n.right} b${n.bottom} l${n.left} z${n.zIndex}`);
  if(n.maxWidth!=='none')bits.push('maxW '+n.maxWidth);
  if(n.flex!=='0 1 auto')bits.push('flex '+n.flex);
  if(n.aspectRatio!=='auto')bits.push('ar '+n.aspectRatio);
  if(n.backgroundColor!=='rgba(0, 0, 0, 0)')bits.push('BG '+n.backgroundColor);
  if(n.backgroundImage!=='none')bits.push('BGIMG '+n.backgroundImage.replace(/https:\/\/framerusercontent\.com\/images\//g,'@/').slice(0,180)+` [${n.backgroundSize} ${n.backgroundPosition} ${n.backgroundRepeat}]`);
  const r=rr(n); if(r)bits.push(r.trim());
  for(const [k,s] of [['bT',n.borderTop],['bR',n.borderRight],['bB',n.borderBottom],['bL',n.borderLeft]]) if(!s.startsWith('0px'))bits.push(k+' '+s);
  if(n.boxShadow!=='none')bits.push('SHADOW '+n.boxShadow);
  if(n.opacity!=='1')bits.push('op '+n.opacity);
  if(n.overflow!=='visible visible')bits.push('of '+n.overflow);
  if(n.transform!=='none')bits.push('TF '+n.transform);
  if(n.transitionDuration!=='0s')bits.push(`TRANS ${n.transitionProperty} ${n.transitionDuration} ${n.transitionTimingFunction}${n.transitionDelay!=='0s'?' delay '+n.transitionDelay:''}`);
  if(n.animationName!=='none')bits.push(`ANIM ${n.animationName} ${n.animationDuration} ${n.animationTimingFunction} x${n.animationIterationCount}`);
  if(n.backdropFilter!=='none')bits.push('BDF '+n.backdropFilter);
  if(n.filter!=='none')bits.push('FILTER '+n.filter);
  if(n.mixBlendMode!=='normal')bits.push('BLEND '+n.mixBlendMode);
  if(n.objectFit!=='fill')bits.push(`objFit ${n.objectFit} @${n.objectPosition}`);
  console.log(`\n${'  '.repeat(Math.max(0,n.depth-4))}${n.tag} ${short}  y${n.y} x${n.x} ${n.w}×${n.h}`);
  console.log(`${'  '.repeat(Math.max(0,n.depth-4))}  ${bits.join(' | ')}`);
  if (n.text || ['p','h1','h2','h3','h4','h5','h6','a','span','li','button'].includes(n.tag))
    console.log(`${'  '.repeat(Math.max(0,n.depth-4))}  TYPE ${n.fontFamily.split(',')[0].replace(/"/g,'')} ${n.fontSize}/${n.lineHeight} w${n.fontWeight} ls${n.letterSpacing} ${n.color} ${n.textAlign}${n.textTransform!=='none'?' '+n.textTransform:''}${n.whiteSpace!=='normal'?' '+n.whiteSpace:''}`);
  if (n.text) console.log(`${'  '.repeat(Math.max(0,n.depth-4))}  TEXT «${n.text.slice(0,90)}»`);
  if (n.img) console.log(`${'  '.repeat(Math.max(0,n.depth-4))}  IMG ${n.img.naturalWidth}x${n.img.naturalHeight} attr ${n.img.attrW}x${n.img.attrH} loading:${n.img.loading||'eager'} sizes:${n.img.sizes||'-'}`);
  if (n.svgAttrs) console.log(`${'  '.repeat(Math.max(0,n.depth-4))}  SVG ${Object.entries(n.svgAttrs).filter(([k])=>!['class','style'].includes(k)).map(([k,v])=>k+'='+String(v).slice(0,220)).join(' ')}`);
}
