import { readFileSync } from 'node:fs';
const d = JSON.parse(readFileSync('raw/ref-1440.json','utf8'));
const N = d.nodes.filter(n=>!['script','style','link'].includes(n.tag) && !n.path.includes('__framer') );
const tally = (fn) => { const m=new Map(); for(const n of N){ const v=fn(n); if(v==null||v==='')continue; m.set(v,(m.get(v)||0)+1);} return [...m].sort((a,b)=>b[1]-a[1]); };
const show = (name, rows, lim=40) => { console.log(`\n== ${name} ==`); rows.slice(0,lim).forEach(([v,c])=>console.log(`  ${String(c).padStart(4)}×  ${v}`)); if(rows.length>lim)console.log(`  … +${rows.length-lim} more`); };

show('COLOR (text)', tally(n=>n.text||['p','h1','h2','h3','h4','h5','h6','a','span','li'].includes(n.tag)?n.color:null));
show('BACKGROUND-COLOR', tally(n=>n.backgroundColor!=='rgba(0, 0, 0, 0)'?n.backgroundColor:null));
show('TYPE ROLE  size/lh weight ls', tally(n=>n.text?`${n.fontSize}/${n.lineHeight} w${n.fontWeight} ls${n.letterSpacing} ${n.fontFamily.split(',')[0].replace(/"/g,'')}`:null));
show('BORDER-RADIUS', tally(n=>{const a=[n.radiusTL,n.radiusTR,n.radiusBR,n.radiusBL];return a.some(v=>v!=='0px')?a.join(' '):null;}));
show('BORDERS', tally(n=>{const s=[n.borderTop,n.borderRight,n.borderBottom,n.borderLeft].map((v,i)=>v.startsWith('0px')?null:['T','R','B','L'][i]+':'+v).filter(Boolean);return s.length?s.join('  '):null;}));
show('BOX-SHADOW', tally(n=>n.boxShadow!=='none'?n.boxShadow:null));
show('GAPS row/col', tally(n=>{const r=n.rowGap,c=n.columnGap;return (r!=='normal'&&r!=='0px')||(c!=='normal'&&c!=='0px')?`${r} / ${c}`:null;}));
show('GRID COLUMNS', tally(n=>n.gridTemplateColumns!=='none'?n.gridTemplateColumns:null));
show('PADDING', tally(n=>{const a=[n.paddingTop,n.paddingRight,n.paddingBottom,n.paddingLeft];return a.some(v=>v!=='0px')?a.join(' '):null;}),30);
show('TRANSITIONS', tally(n=>n.transitionDuration!=='0s'?`${n.transitionProperty} | ${n.transitionDuration} | ${n.transitionTimingFunction} | delay ${n.transitionDelay}`:null));
show('ANIMATIONS', tally(n=>n.animationName!=='none'?`${n.animationName} ${n.animationDuration} ${n.animationTimingFunction} x${n.animationIterationCount} ${n.animationDirection}`:null));
show('BACKDROP-FILTER', tally(n=>n.backdropFilter!=='none'?n.backdropFilter:null));
show('FILTER', tally(n=>n.filter!=='none'?n.filter:null));
show('GRADIENTS', tally(n=>n.backgroundImage.startsWith('linear')||n.backgroundImage.startsWith('radial')?n.backgroundImage:null));
show('OPACITY <1', tally(n=>n.opacity!=='1'?n.opacity:null));
show('SECTION X/W (depth<=5, w>400)', tally(n=>n.w>400&&n.depth<=5?`x${n.x} w${n.w}`:null));
console.log('\n== IMAGES ==');
N.filter(n=>n.img).forEach(n=>console.log(`  ${n.w}×${n.h}  nat ${n.img.naturalWidth}×${n.img.naturalHeight}  attr ${n.img.attrW}×${n.img.attrH}  objFit ${n.objectFit} @${n.objectPosition}  loading ${n.img.loading||'eager'}  sizes ${n.img.sizes||'-'}\n      y${n.y} x${n.x}  ${n.img.currentSrc.replace('https://framerusercontent.com/images/','@/')}`));
